import { Card, CardContent, Box, Chip, Button } from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';
import dayjs from 'dayjs';
import { useQuery } from '@tanstack/react-query';

import PageHeader from '../../components/common/PageHeader';
import { TableSkeleton, Empty } from '../../components/common/States';
import { payrollService } from '../../services';
import { formatCurrency } from '../../lib/format';
import api from '../../lib/api';

export default function MyPayrollPage() {
  const { data, isLoading } = useQuery({ queryKey: ['my-payroll'], queryFn: payrollService.mine });

  const downloadPayslip = async (id) => {
    try {
      const res = await api.get(`/payroll/${id}/payslip`, { responseType: 'blob' });
      const url = URL.createObjectURL(res.data);
      const a = document.createElement('a');
      a.href = url; a.download = `payslip-${id}.pdf`; a.click();
      URL.revokeObjectURL(url);
    } catch {}
  };

  return (
    <>
      <PageHeader title="My Payslips" subtitle="Download your monthly salary slips" />
      <Card><CardContent>
        {isLoading ? <TableSkeleton /> : (data?.data?.length ? (
          <Box sx={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead><tr style={{ textAlign: 'left' }}>{['Month', 'Basic', 'Commission', 'Bonus', 'Deductions', 'Net Salary', 'Status', 'Action'].map((h) => (
                <th key={h} style={{ padding: '10px 8px', fontSize: 12, opacity: 0.7, borderBottom: '1px solid rgba(0,0,0,0.08)' }}>{h}</th>
              ))}</tr></thead>
              <tbody>
                {data.data.map((p) => (
                  <tr key={p._id} style={{ borderBottom: '1px dashed rgba(0,0,0,0.08)' }}>
                    <td style={{ padding: '10px 8px', fontWeight: 600 }}>{dayjs(`${p.year}-${p.month}-01`).format('MMMM YYYY')}</td>
                    <td style={{ padding: '10px 8px' }}>{formatCurrency(p.basicSalary)}</td>
                    <td style={{ padding: '10px 8px' }}>{formatCurrency(p.commission)}</td>
                    <td style={{ padding: '10px 8px' }}>{formatCurrency(p.attendanceBonus + p.incentives + p.overtime)}</td>
                    <td style={{ padding: '10px 8px', color: '#ef4444' }}>−{formatCurrency(p.lateDeduction + p.absentDeduction + p.otherDeductions)}</td>
                    <td style={{ padding: '10px 8px', fontWeight: 800, color: '#1aab50' }}>{formatCurrency(p.netSalary)}</td>
                    <td style={{ padding: '10px 8px' }}><Chip size="small" label={p.status} color={p.status === 'PAID' ? 'success' : 'default'} /></td>
                    <td style={{ padding: '10px 8px' }}>
                      <Button size="small" startIcon={<DownloadIcon />} variant="contained" onClick={() => downloadPayslip(p._id)}>Download</Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Box>
        ) : <Empty title="No payslips yet" subtitle="Your payslips will appear here once generated by HR." />)}
      </CardContent></Card>
    </>
  );
}
