module.exports = {
  ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    HR_MANAGER: 'HR_MANAGER',
    TEAM_LEADER: 'TEAM_LEADER',
    EMPLOYEE: 'EMPLOYEE',
  },
  ATTENDANCE_STATUS: {
    PRESENT: 'PRESENT',
    ABSENT: 'ABSENT',
    LEAVE: 'LEAVE',
    HOLIDAY: 'HOLIDAY',
    LATE: 'LATE',
    HALF_DAY: 'HALF_DAY',
  },
  ATTENDANCE_METHOD: {
    LOGIN: 'LOGIN',
    FINGERPRINT: 'FINGERPRINT',
    MANUAL: 'MANUAL',
  },
  LEAVE_TYPES: ['CASUAL', 'SICK', 'ANNUAL', 'EMERGENCY'],
  LEAVE_STATUS: { PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED' },
  TARGET_TYPES: ['ONCE', 'WEEKLY', 'MONTHLY'],
  EMP_STATUS: ['ACTIVE', 'INACTIVE', 'TERMINATED', 'ON_LEAVE'],
};
